### PR TITLE
create: Profile card component created

### PR DESCRIPTION
**Pull request by arjun-computer-geek**
Made card component 
Profile card

### CODE REVIEW

**Comment by mikesch803** [comment]
LGTM

**Review by mikesch803 — APPROVED** [review]

**Review by Shubhamkr2610 — APPROVED** [review]
looks good to me .

**Review by ashishnnnnn — APPROVED** [review]
Code seems fine and structured :+1:

**Review by ArjunJunna — APPROVED** [review]
looks good to me

**Review by Developers-codz — APPROVED** [review]
Looks Good to me!

**Pull request merged**
